### PR TITLE
Add LightingAutomationSystem to Building and LightingSystem

### PR DESCRIPTION
**Pull request by macintoshpie**

### CODE REVIEW

**Review by markborkum — APPROVED** [review]
Changes look good, thanks.

**Review by corymosiman12 — CHANGES_REQUESTED** [review]
I think LightingManagementSystem is more of the industry term than LightingAutomationSystem.  Nothing provided by BEDES dictionary or ASHRAE terminology.  @nllong ??

**Comment by macintoshpie** [comment]
Nick confirmed that Lighting Automation System is the best option.

**Review by corymosiman12 — APPROVED** [review]
Thanks for confirming, lgtm.

**Pull request merged**
