### PR TITLE
Java files for ASHRAE 211 Mapping

### PR DESCRIPTION
**Pull request by hecsonline**

### CODE REVIEW

**Comment by nllong** [comment]
i'm a little concerned that there are over 2,800 files that are changed/added here. can you shed some light on this?

**Comment by hecsonline** [comment]
Wow, I knew there were a lot but I didn't know it was that many. Let me try
just the input files for Java.

On Tue, Apr 12, 2016 at 9:02 AM, Nicholas Long <notifications@github.com>
wrote:

> i'm a little concerned that there are over 2,800 files that are
> changed/added here. can you shed some light on this?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/BuildingSync/schema/pull/10#issuecomment-208950241>
>



-- 
Robert Hendron
Hendron Energy Consulting Services
720-331-3537
bob@hecsonline.com

**Comment by nllong** [comment]
@hecsonline it looks like there are some tests failing after you added the 211 examples.

If you follow the ci link you will see

```
Validating examples/ashrae211.xml
[{:file=>"examples/ashrae211.xml",
  :error=>
   #<Nokogiri::XML::SyntaxError: Element '{http://nrel.gov/schemas/bedes-auc/2014}ElectricitySourcedFromOnsiteRenewableSystems': '234.466588511137162954279015240328253223915592028135990621336459555' is not a valid value of the atomic type 'xs:decimal'.>}]
There were 1 errors
F
```

So for some reason 234.466588511137162954279015240328253223915592028135990621336459555 is not a valid decimal. It looks valid, but I'm guessing it has to do with sig figs. That is one precise number.

Can you fix this in the translation?

**Comment by hecsonline** [comment]
Nick,

Is that an error when running the Java version, or when validating the file
in XML Spy?

Bob

On Tue, Apr 26, 2016 at 11:02 AM, Nicholas Long <notifications@github.com>
wrote:

> @hecsonline <https://github.com/hecsonline> it looks like there are some
> tests failing after you added the 211 examples.
>
> If you follow the ci link you will see
>
> Validating examples/ashrae211.xml
> [{:file=>"examples/ashrae211.xml",
>   :error=>
>    #<Nokogiri::XML::SyntaxError: Element '{http://nrel.gov/schemas/bedes-auc/2014}ElectricitySourcedFromOnsiteRenewableSystems': '234.466588511137162954279015240328253223915592028135990621336459555' is not a valid value of the atomic type 'xs:decimal'.>}]
> There were 1 errors
> F
>
> So for some reason
> 234.466588511137162954279015240328253223915592028135990621336459555 is not
> a valid decimal. It looks valid, but I'm guessing it has to do with sig
> figs. That is one precise number.
>
> Can you fix this in the translation?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/BuildingSync/schema/pull/10#issuecomment-214812139>
>



-- 
Robert Hendron
Hendron Energy Consulting Services
720-331-3537
bob@hecsonline.com

**Comment by nllong** [comment]
it uses nokogiri which uses libxml to validate. here is the validation test.

https://github.com/BuildingSync/schema/blob/develop/test/validation_test.rb

to run locally you need ruby installed, then run

```
bundle
rake test
```

18 digits max.

**Comment by nllong** [comment]
@hecsonline I just merged this down. Make sure that you create a new branch the next time you add/fix something. Make the branch names somewhat self explanatory.

**Pull request merged**
