### PR TITLE
refactor: allow versions without PATCH included

### PR DESCRIPTION
**Pull request by macintoshpie**
#### Any background context you want to provide?
The root BuildingSync element has an `@version` attribute allowing users to specify the version of their document. We have been writing the full version, `MAJOR.MINOR.PATCH`, as the choices. This is not compatible with creating patch releases though -- since the `x.x.0` version was already released, it will consider any new patch version to be invalid according to that schema.

⚠️  From now on, we should _only_ add these `MAJOR.MINOR` versions!

#### What does this PR do?
- Use `MAJOR.MINOR` versions when specifying versions (but allow the old MAJOR.MINOR.PATCH to stick around)

#### What are the relevant tickets?

#414

### CODE REVIEW

**Review by JieXiong9119 — APPROVED** [review]
Nice and neat!

**Review by Ryoken — APPROVED** [review]
Nice and easy!

**Review by markborkum — APPROVED** [review]
Changes look good, thanks.

**Review by nllong — APPROVED** [review]
looks stellar!

**Pull request merged**
