### PR TITLE
Add AuditorQualificationType enumerations

### PR DESCRIPTION
**Pull request by markborkum**
See `proposals/2019/Add AuditorQualificationType enumerations.md` for details.

### CODE REVIEW

**Comment by nllong** [comment]
@supriyagoel  -- we can remove PhD from qualification types, correct?

**Comment by markborkum** [comment]
@nllong Not at this stage. "PhD in Mechanical Engineering" is still a valid qualification type in Audit Template.

**Comment by nllong** [comment]
How does <xs:enumeration value="American Society of Heating, Refrigeration, and Air-Conditioning Engineers (ASHRAE)"/> differ from <xs:enumeration value="ASHRAE Building Energy Assessment Professional (BEAP)"/>?

**Comment by markborkum** [comment]
@nllong I've been thinking about that too. It may be referring to BCxP and/or BEMP certifications (since BEAP and HBDP are already present in the enumeration). In which case, we should add those instead.

@supriyagoel In Audit Template, does the "Other ASHRAE ..." certification type refer to BCxP and/or BEMP?

**Comment by supriyagoel** [comment]
@nllong - we're looking into 'phd in mech eng' qualification. I dont think any city requested it but checking to make sure
@markborkum i see 'Other Approved or Equivalent Qualifications' which could refer to any qualification a jurisdiction identifies as appropriate, not necessarily only BEMP or BCxP. Even if we add those two qualifications to BuildingSync, we should still allow 'Other' as an input.

**Comment by markborkum** [comment]
@supriyagoel, No-one is suggesting that we remove the "Other" enumeration from BuildingSync.

@nllong Sounds like we should swap
```
<xs:enumeration value="American Society of Heating, Refrigeration, and Air-Conditioning Engineers (ASHRAE)"/>
```
for BxCP and BEMP.

**Comment by nllong** [comment]
@markborkum swapping sounds good. I don't think I can make the change since this is on your fork. Can you make the change?

**Comment by markborkum** [comment]
@nllong, I went ahead and added the full set of AEE, AABC and ASHRAE certifications.

**Comment by supriyagoel** [comment]
@nllong Looks like the 'PhD in Mechanical Engineering' was requested by SF over a year ago and never made it to our list of requests for BuildingSync. we would need to add this- hope thats ok

**Comment by nllong** [comment]
got it. no changes needed then since it is already in there. thanks for
double/triple checking

**Pull request merged**
