### PR TITLE
Add FacilityEvaluationAuditDefinition

### PR DESCRIPTION
**Pull request by JieXiong9119**
#### Any background context you want to provide?
FEMP CERL use case

#### What does this PR do?
See proposal

#### What are the relevant tickets?
#466

### CODE REVIEW

**Comment by markborkum** [comment]
@JieXiong9119, Since the FEMP document is still a draft, it may be too early to add this new XML element to the schema.

For example, if the FEMP document changes, since the proposal is to introduce a 2-level hierarchical structure, moving a level-2 child to a different level-1 parent would be a breaking change.

**Comment by markborkum** [comment]
@JieXiong9119, I'm not convinced that adding a hierarchy is going to add value. Having a "plain" enumeration would be easier to maintain.

**Comment by JieXiong9119** [comment]
That's reasonable. We can hold it off a bit. Do you have any idea when the FEMP resource would be finalized?

**Comment by markborkum** [comment]
@JieXiong9119,

> Do you have any idea when the FEMP resource would be finalized?

I don't, sorry. We'd need to ask a FEMP representative. I know that an updated version of the "decision tree" document was recently published (https://www.energy.gov/femp/articles/femp-facility-evaluation-audit-decision-tree), but I don't know if it is the final version that we should be targeting.

**Comment by markborkum** [comment]
@ThibaultMarzullo, Adding "Retro-Commissioning Audit" (non-BEDES spelling) was requested by CERL.

In Audit Template, the enumerations were sourced from https://www.energy.gov/sites/default/files/2020/12/f81/facility-evaluation-definitions.pdf which appears to be an earlier (out-of-date?) draft of the FEMP guidance.

**Comment by ThibaultMarzullo** [comment]
> @ThibaultMarzullo, Adding "Retro-Commissioning Audit" (non-BEDES spelling) was requested by CERL.

Thank you! I'll approve then.

> In Audit Template, the enumerations were sourced from https://www.energy.gov/sites/default/files/2020/12/f81/facility-evaluation-definitions.pdf which appears to be an earlier (out-of-date?) draft of the FEMP guidance.

Are there any major changes you have noticed?

**Review by ThibaultMarzullo — APPROVED** [review]

**Comment by markborkum** [comment]
@ThibaultMarzullo, Comparing https://www.energy.gov/sites/default/files/2020/12/f81/facility-evaluation-definitions.pdf and https://www.energy.gov/femp/articles/femp-facility-evaluation-audit-definitions, I don't see any new/modified audit definitions. That said, it is possible that the second link is also outdated. We should ask a FEMP representative for the most recent version.

**Comment by JieXiong9119** [comment]
@markborkum, after circling around FEMP and PNNL teams, the document is confirmed to be the latest version. We will proceed to merge this down if you see no other issues.

**Review by markborkum — APPROVED** [review]
@JieXiong9119, No issues from me, thanks!

**Pull request merged**
