### PR TITLE
SHW units add COP

### PR DESCRIPTION
**Pull request by fieldkm**
Added option to specify efficiency of SHW/DHW heater as COP, in addition to existing Thermal Efficiency and Energy Factor.

Added a heat pump water heater (DHW2) to PrimarySchoolCRB1.xml example file.  Gave it COP of 2.0.  Divided daily draw between this and DHW1 so that the Reb Bldg flows were maintained.

### CODE REVIEW

**Comment by jasondegraw** [comment]
@fieldkm I'm confused about the first commit that is listed here. It doesn't look right. Any ideas on where that is coming from?

The other two commits look fine.

**Comment by fieldkm** [comment]
@jasondegraw I agree it's weird, but my understanding is that it's a "merge commit" that's harmless.  Here's where I'm getting the "harmless" assumption from: https://stackoverflow.com/questions/10157702/why-did-git-create-a-merge-commit-with-no-file-changes
I may have switched from a fieldkm remote branch at an awkward time, but it didn't involve any file changes.

**Comment by jasondegraw** [comment]
The commit message is pretty confusing, so I'll see if I can remove it.

**Comment by fieldkm** [comment]
@jasondegraw  do you think it's ok to merge this now?

**Comment by fieldkm** [comment]
@jasondegraw never mind

**Pull request closed without merging**
