### PR TITLE
General: Annotations and Version Tag

### PR DESCRIPTION
**Pull request by nllong**
General cleanup changes.

* Periods at end of annotations
* Units in ( ) and not []
* 0-1 or 0-100 (fraction vs %)
* square ft to ft2
* e.g.,

### CODE REVIEW

**Comment by jasondegraw** [comment]
@nllong Would now be a good time to fix the percentage/fraction docs? I'm on my phone so it's hard to link to an example, but we have documentation strings that say [0,1] for percentages (and possibly the other way around). We could enforce (in validation) the range, but it'd be good to have the docs correct in any case.

**Comment by nllong** [comment]
@jasondegraw - yes. If you see any of those, just put them on this PR. There are many of those.

**Comment by markborkum** [comment]
@nllong, Does this close #73?

**Comment by nllong** [comment]
@markborkum, indeed it does. Thanks for catching that.

**Pull request merged**
