### PR TITLE
remove tabs

### PR DESCRIPTION
**Pull request by nllong**

### CODE REVIEW

**Comment by nllong** [comment]
@jasondegraw @fieldkm The HighLevel.xml example is failing because the `TypicalOccupantUsages` element doesn't to appear to be in the schema. Not sure if it moved  or something happened with the merge. I cleaned up the MeasureFirstCost and all the tabs in the files.

**Comment by jasondegraw** [comment]
Yeah, there was some sort of merge failure here that removed `TypicalOccupantUsages`. Should we re-add it, or try to fix the merge some other way?

**Comment by nllong** [comment]
I suggest that we just re-add it.

**Comment by jasondegraw** [comment]
I think we've got bigger problems than just `TypicalOccupantUsages`, looking at the diff with whitespace ignored shows other things may now be missing:

https://github.com/BuildingSync/schema/pull/22/files?w=1

I'm not sure what is intended and what is not. @nllong Any ideas? I think we need to (sorry!) try again.

**Comment by nllong** [comment]
i can try again... does develop look right?

**Comment by jasondegraw** [comment]
@nllong Yes, it does.

**Comment by nllong** [comment]
something strange is going on... closing and will try again after next round of changes.

**Pull request closed without merging**
