### PR TITLE
proposal: add proposal and implementation for LightingPowerDensity

### PR DESCRIPTION
**Pull request by corymosiman12**

### CODE REVIEW

**Comment by markborkum** [comment]
In Audit Template, lighting power density is an attribute of the reified relationship between a fixture and a space function. Audit Template also distinguishes between LPDs for different "types", e.g., common, gross, tenant, etc.

Q1: Should the new element be a child of `auc:LightingSystemType` or `auc:LightingSystemType/auc:LinkedPremises` (like the `auc:FloorAreas` element)?
Q2: Should the new element be `auc:LightingPowerDensities` (in the same style as the `auc:FloorAreas` element) to support values for different sub-space types?
Q3: Is there a plan for other attributes of the reified relationship, e.g., the number of fixtures (by "type")?

**Review by macintoshpie — COMMENTED** [review]
This looks good to me, just wanted to double check there's not another term for this that might be in BEDES though.

**Comment by corymosiman12** [comment]
@markborkum , let me see if I understand.

> In Audit Template, lighting power density is an attribute of the reified relationship between a fixture and a space function.

You all have some function to determine, given a space function (Office) and a fixture type (LED), the value of an LPD?  Where does this come from?

This makes sense for the perspective that the LPD is unknown by the auditor. LPDs (I believe) may be known, so there might be a need to allow this to be reported separately from declaring a fixture / fixture type.

The other questions are good ones.  I think #2 is a good design concept if I understand it correctly:
- A `LightingSystem` of type `LED` is declared
- This could be linked to a section to declare this lighting type is applicable to that section.  That section, though, might have multiple sub space types (kitchen, open office, closed office, etc.), which you could then declare different LPDs for each of those

That a correct understanding?  If so, seems reasonable.

**Comment by markborkum** [comment]
.@corymosiman12 

> You all have some function to determine, given a space function (Office) and a fixture type (LED), the value of an LPD? Where does this come from?

Not exactly. The different LPDs are attributes of the association between the model class for an Audit Template lighting system and the model class for an Audit Template space function, which is itself associated with the model class for an Audit Template building. The LPD values are user-provided, i.e., not calculated.

Currently, the LPD values are asserted as `auc:UserDefinedFields` of the `auc:LightingSystem` element, e.g., https://github.com/BuildingSync/schema/blob/develop/examples/AT_example_NYC_audit_report_property.xml#L2617-L2628. (In the example, the same approach is used to assert "Quantity of Luminaires" values.)

**Comment by corymosiman12** [comment]
Hey @markborkum - if the LPDs are not calculated and are specific to the relationship btw. a lighting system and a space function, the remaining question from my perspective is: Is there a lighting system defined for every space function?

In BSync L1 audit, we require every Section[SectionType='Space function'] to have a Lighting System defined ([here](https://github.com/BuildingSync/TestSuite/blob/8b5f3ec69d1c818a0cf1643cb2d39c35c9245764/schematron/v2.2.0/v2-2-0_L100_Audit.sch#L111)).  From that perspective, it seems reasonable that a LightingSystem with an LPD property makes sense - similar to the way `InstalledPower` and `LampPower` are already used.

In looking at the ATT stuff, certain templates do break it out into Common / Tenant (NYC), but others don't (ASHRAE Level 2).  Although in neither of those was I able to specify LPD (what am I missing?).  In ATT, the perspective for a Fixture (which I assume gets translated to a BSync LightingSystemType) seems to define LightingSystemType as a unique combination of: Lighting Type, Ballast Type, Controls.  This LightingSystemType is then 'applied' to different Sections of the building.

It seems, therefore, that we are using LightingSystemType in two different ways:
- BSync perspective: a LightingSystem is the system used for a specific space function within a building.  
- ATT perspective: a LightingSystemType is a unique combination of a Lighting Type (auc:LampType), ballast type (auc:BallastType) and controls (auc:Control) (although looks like multiple LightingSystems with the same combinations can be created).

I think we should discuss this on our next call.  @nllong thoughts?

**Comment by markborkum** [comment]
.@corymosiman12 Yes. In fact, in Audit Template, the relationship between (interior) lighting systems and space functions is many-to-one.

The LPD, number of fixtures, etc. are attributes of the reified, directed association between the lighting system and the space function (and not the lighting system itself or the space function itself). This is why it would be useful for said attributes to be child elements of the `auc:LinkedPremises` element.

**Pull request closed without merging**
