### PR TITLE
Refactor/remove duplicates

### PR DESCRIPTION
**Pull request by Ryoken**
#### Any background context you want to provide?
There are duplicate elements that need to be removed.

#### What does this PR do?
Consolidates all duplicate elements.

#### How should this be manually tested?
`bundle exec rake` should pass

#### What are the relevant tickets?
https://github.com/BuildingSync/schema/issues/323
https://github.com/BuildingSync/schema/issues/324
https://github.com/BuildingSync/schema/issues/325

### CODE REVIEW

**Review by macintoshpie — APPROVED** [review]
Wow, ~2k lines less! That's awesome.

Because this was so much I wasn't really able to meticulously look at every change.

To convince myself (and others) that this is a non-breaking change, ie that we only refactored the elements into shared elements for reference, I generated multiple v2.3.0 files using oxygenxml. Below is the workflow I used:

1. Download v2.3.0 xsd from releases page.
2. Use the `Generate Sample XML Files` Tool in OxygenXML. See the config below. I've also attached a zip file of these generated buildingsync files. The important configuration settings are "generate optional elements" and "attributes" are both enabled, with a "preferred number of repetitions" of 2, so we are guaranteed all optional elements. In addition I set the "discard optional elements after nested level" to 100, so I don't think we'd be dropping any optional elements that deep.
[bsync_examples.zip](https://github.com/BuildingSync/schema/files/6518391/bsync_examples.zip)

Screen Shot 2021-05-20 at 1 29 50 PM
Screen Shot 2021-05-20 at 1 30 00 PM
Screen Shot 2021-05-20 at 1 30 07 PM
Screen Shot 2021-05-20 at 1 30 15 PM
Screen Shot 2021-05-20 at 1 30 22 PM
3. I validated all of the generated instances against this PR's version of the schema. **None of the instances failed validation.**

```python
from pathlib import Path
import xmlschema

instances = (Path.home() / 'Downloads/bsync_examples').rglob('*.xml')
schema_path = 'BuildingSync.xsd'
schema = xmlschema.XMLSchema(str(schema_path))

for i, instance in enumerate(instances):
    print(f'Validating {instance}')
    try:
        xmlschema.validate(str(instance))
    except Exception as e:
        print(f'FAILED {instance}')
        raise e
```

I feel 99% confident this is a non-breaking change. In the future it might help to break these changes into separate PRs.

**Comment by nllong** [comment]
Can you resolve the conflict por favor?

**Review by nllong — APPROVED** [review]
This is great. Thanks Ted for the comprehensive non-breaking change check.

This is going to be a doozy to merge into develop-v3, I expect.

Also, can one of you confirm that Selection Tool is still happy parsing this schema?

**Comment by Ryoken** [comment]
> Can you resolve the conflict por favor?

Resolved!  The only issue was with the list of duplicates in the validator so I don't believe there needs to be any additional testing.

**Comment by macintoshpie** [comment]
> Resolved! The only issue was with the list of duplicates in the validator so I don't believe there needs to be any additional testing.

@Ryoken Looks like some ones we removed snuck back in there, could you remove those again? (left is diff after original spec update, right is diff after post-merge)

Screen Shot 2021-05-20 at 4 05 42 PM

**Comment by Ryoken** [comment]
> This is great. Thanks Ted for the comprehensive non-breaking change check.
> 
> This is going to be a doozy to merge into develop-v3, I expect.
> 
> Also, can one of you confirm that Selection Tool is still happy parsing this schema?

I just ran it through the Selection Tool again, added it as a new schema and validated a few sample XMLs with it.

**Comment by Ryoken** [comment]
> > Resolved! The only issue was with the list of duplicates in the validator so I don't believe there needs to be any additional testing.
> 
> @Ryoken Looks like some ones we removed snuck back in there, could you remove those again? (left is diff after original spec update, right is diff after post-merge)
> 
> Screen Shot 2021-05-20 at 4 05 42 PM

You're right, it looks like a recent merge added a couple new duplicates.  I pulled those out and updated the PR!

**Comment by JieXiong9119** [comment]
Should we bring this to `develop-v3` branch as well?

**Comment by macintoshpie** [comment]
@JieXiong9119 yes, can you open that PR?

**Pull request merged**
