### PR TITLE
Refactor Measurename minOccurs maxOccurs

### LINKED ISSUE #268: Consider auc:MeasureName Refactor to minOccurs=1 maxOccurs=1

### PR DESCRIPTION
**Pull request by JieXiong9119**
See proposal.

Resolves #268

### CODE REVIEW

**Review by nllong — APPROVED** [review]
nice, now only one measure name per measure. Thanks!

**Review by macintoshpie — APPROVED** [review]
Nice!

**Comment by nllong** [comment]
Who originated this request? I think it was Maalka, correct? If so, then I can shoot them a message to review. Let me know.

**Comment by JieXiong9119** [comment]
> Who originated this request? I think it was Maalka, correct? If so, then I can shoot them a message to review. Let me know.

The ticket was opened by Cory.

**Comment by rimasgulbinas** [comment]
this looks good and is exactly what we were hoping for. thanks!

**Pull request merged**
