### PR TITLE
Add fenestration system measures

### PR DESCRIPTION
**Pull request by JieXiong9119**
#### Any background context you want to provide?
See #490 .

#### What does this PR do?
See proposal.

#### What are the relevant tickets?
#490

### CODE REVIEW

**Comment by JieXiong9119** [comment]
Please hold yourr review before we get feedbacks from Measure Naming expert.

**Review by markborkum — APPROVED** [review]
Looks good to me. Thanks, Jie!

**Review by ThibaultMarzullo — COMMENTED** [review]
Thanks Jie, this looks good! I reviewed this and will hold until after we received feedback on measure names. Can you reach out to the PNNL team that has suggested the measures and invite them to review this PR please? I'd like to keep them in the loop in case they want to comment before we implement changes.

**Review by ThibaultMarzullo — APPROVED** [review]

**Comment by JieXiong9119** [comment]
We did not hear back from 1836-RP team, so we'll use the instruction in "Best Practices for Measure Names: Lessons from 1836-RP" (previously for WCMs review) for measure naming guidance.

**Pull request merged**
