### PR TITLE
Deprecate PrimaryHVACSystemType

### LINKED ISSUE #230: Deprecate PrimaryHVACSystemType element
Now that `auc:PrincipalHVACSystemType` was added in #215 , remove the choice to use `auc:PrimaryHVACSystemType` in schema v3.0.

### PR DESCRIPTION
**Pull request by JieXiong9119**
See proposal.

Resolves #230

### CODE REVIEW

**Comment by macintoshpie** [comment]
@JieXiong9119 maybe we could add a transformation to the xslt for making this conversion?

**Review by nllong — APPROVED** [review]
This looks good! I'm not going to merge since it looks like we may be waiting for the transformation.

**Comment by nllong** [comment]
I don't think we need an XSLT on this one since we have warned that we are deprecating. Feel free to disagree, but I think we can merge this one for now.

**Comment by macintoshpie** [comment]
> I  don't think we need an XSLT on this one since we have warned that we are deprecating. Feel free to disagree, but I think we can merge this one for now.

I think we still might want to include it in xslt, but I agree let's merge it

**Comment by JieXiong9119** [comment]
> I don't think we need an XSLT on this one since we have warned that we are deprecating. Feel free to disagree, but I think we can merge this one for now.

I have included this change in the updated XSLT in this PR #360 simply by renaming it to the correct one. I think it's better to have all "breaking changes" covered by the XSLT.

**Pull request merged**
