### PR TITLE
Supriya comments apr16

### PR DESCRIPTION
**Pull request by fieldkm**

### CODE REVIEW

**Comment by fieldkm** [comment]
For some reason, the schema is showing very unhelpful diffs, even though my one change was very minor.  I think it may have to do with the way XML Spy adds spaces/tabs vs. how the original file had them.  Maybe I need to change a default setting?  Anyway, we may want to correct this before I make other changes so that everything can have useful diffing possible. --Kristin

**Comment by nllong** [comment]
This broke the example files because the space IDs are in the examples. Do you want to clean those up too?

**Comment by fieldkm** [comment]
Sure, I can do this.  Is that why the CircleCI test failed?

**Comment by nllong** [comment]
yep

**Comment by fieldkm** [comment]
@nllong is this ok now?

**Comment by nllong** [comment]
perfect. thanks!

**Pull request merged**
