### PR TITLE
Proposal to add UBID

### PR DESCRIPTION
**Pull request by nllong**
See the proposals/2018/add ubid.md

### CODE REVIEW

**Comment by nllong** [comment]
If you have a list of similar identifiers, then sure, let's add them, else, I say we stick to this single addition for now.

**Comment by nllong** [comment]
The one that I can think of know is BBL, should we add that?

**Comment by jasondegraw** [comment]
@nllong Maybe the thing to do is to add a new issue and we can collect up the possibilities there. How about that?

**Comment by nllong** [comment]
That seems reasonable. Let's do that on the next round (after dec release).

**Pull request merged**
