### PR TITLE
proposal: add proposal to limit MeasureName occurrences

### PR DESCRIPTION
**Pull request by macintoshpie**
Also see #268

### CODE REVIEW

**Review by corymosiman12 — APPROVED** [review]

**Review by nllong — APPROVED** [review]
seems reasonable.

**Comment by corymosiman12** [comment]
@markborkum - thoughts?

**Review by markborkum — APPROVED** [review]
Proposal looks good, thanks.

**Comment by nllong** [comment]
As this is a breaking change, we will handle in version 3.0.

**Pull request closed without merging**
